### ISSUE TITLE
Make story analytics variable names consistent

### ISSUE THREAD

**Issue by rudygalfi** [newmuis/amphtml-story#154]
I was reviewing the story analytics spec and noticed that

`${pageId}` maps to `STORY_PAGE_ID`
`${pageIndex}` maps to `STORY_PAGE_INDEX`

We should make consistent, i.e.

`${storyPageId}` maps to `STORY_PAGE_ID`
`${storyPageIndex}` maps to `STORY_PAGE_INDEX`

**Comment by newmuis** [comment]
Migrated to ampproject/amphtml#11648.
