### ISSUE TITLE
Where is the amp-story.md mentioned in the description of this repo?

### ISSUE THREAD

**Issue by dandv** [newmuis/amphtml-story#195]
![image](https://user-images.githubusercontent.com/33569/33918917-d69b0bfe-df6a-11e7-92d1-1f504e2d1031.png)

Searching for the file in the repo ultimately landed me at https://github.com/ampproject/amphtml/blob/master/extensions/amp-story/amp-story.md

**Comment by ithinkihaveacat** [comment]
Yeah, this repo isn't used anymore--everything's been merged into https://github.com/ampproject/amphtml. (How did you come across it?)

And yes, that file is the best documentation of the `<amp-story>` component.
